### ISSUE TITLE
[LDC][DUB] test failed

### ISSUE THREAD

**Issue by 9il** [kyllingstad/scid#19]
`dub test --compiler=ldc2` failed.

See https://travis-ci.org/9il/scid/jobs/46697648
or https://travis-ci.org/kyllingstad/scid/jobs/46697692

**Comment by kyllingstad** [comment]
It looks to me like LDC is crashing, making this an LDC bug. Have you reported it there?

**Comment by 9il** [comment]
https://github.com/ldc-developers/ldc/issues/823

**Comment by kyllingstad** [comment]
Fixed in LDC (and also not relevant to SciD anymore).
