### ISSUE TITLE
readme is outdated

### ISSUE THREAD

**Issue by 9il** [kyllingstad/scid#23]
Please update README after #22. I think few words about building with dub, Travis CI shield and link to the documentation http://ddocs.org/scid/latest/scid/functions.html can help users.

**Comment by kyllingstad** [comment]
I'll update the README. I didn't know about ddocs.org, that's pretty cool!

**Comment by kyllingstad** [comment]
Fixed: ab6b4c60cae05dc8053fdd24da525a72f2294744
