### ISSUE TITLE
Build script should allow choice of compiler

### ISSUE THREAD

**Issue by WebDrake** [kyllingstad/scid#5]
If I understand correctly, the current build script hardcodes in dmd as the compiler.  This is undesirable for a couple of reasons.

* gdc produces much faster code, so if you're in a position to compile with gdc this is preferable :-)

* Some Linux distros (e.g. Debian) have strict rules about proprietary dependencies; a reliance on dmd will block packaging of SciD.  Of course, it's trivial to manually tweak the build script, but nicer to make it so they don't have to.

* ... related: it's not clear to me that the build script allows you to set optimization flags.  This would be nice to have as well.

**Comment by kyllingstad** [comment]
Fixed a long time ago, just forgot to close it then.
